### ISSUE TITLE
ssl cert verification error how to set it false?

### ISSUE THREAD

**Issue by phanikumar944** [crow1011/wazuh2thehive#3]

**Comment by crow1011** [comment]
Hi @phanikumar944 
Please describe your problem in more detail so that I can help you

**Comment by phanikumar944** [comment]
While integrating to hive public ip I got error SSL certificate ... Is there any extra I can add to config file to .like .SSL.verification false I tried but issue not solved.

**Comment by crow1011** [comment]
You can change line 61 in the file
/var/ossec/integrations/custom-w2thive.py
on the
thive_api = TheHiveApi(thive, thive_api_key, cert=False)
this (cert=False) should disable certificate validation.

Unfortunately, I can't test this solution right now. Please tell me if it helps.

**Comment by AC-WhiteGlint** [comment]
Hi,

I tried you solution but it doesn't work : 

thehive4py.exceptions.AlertException: Alert create error: HTTPSConnectionPool(host='192.168.1.139', port=10000): Max retries exceeded with url: /api/alert (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))

**Comment by crow1011** [comment]
Hi @AC-WhiteGlint 
I have no idea how to help you but try this:
______________________________________________
Check the functionality of TheHive with this script:
https://github.com/TheHive-Project/TheHive4py/blob/1.x/samples/test-alert-create.py
Edit the line
(16) api = TheHiveApi ('http://127.0.0.1:9000', '** YOUR_API_KEY **')
enter your host and api-key and run this
This will create a test alert
___________________________________________________________
sudo /var/ossec/framework/python/bin/pip3 list

save the list of libraries to a file

sudo/var/ossec/framework/python/bin/pip3 install requests

If this does not help, install the version of requests from the file

sudo /var/ossec/framework/python/bin/pip3 install requests == <version>
______________________________________________________
Please attach your integration configuration from the ossec.conf file in the answer

**Comment by AC-WhiteGlint** [comment]
So, I think the issue was coming from TheHive.

I am now running TheHive 4.1.4-1 and I didn't even needed to change anyhting not even setting the ssl verification to false.

You cna slose this issue.

You plugin is working perfectly!

Thank you!
